### ISSUE TITLE
Hyperlink error in README.md

### ISSUE THREAD

**Issue by jwpestrak** [opendatagroup/hadrian#14]
Selecting the Portable Format for Analytics (PFA) hyperlink (in Chrome) results in an error -

"""
This site can’t be reached

scoringengine.org’s server DNS address could not be found.
"""

**Comment by jpivarski** [comment]
That's a broken link because `scoringengine.org` has been disbanded in favor of `dmg.org/pfa`. Where is that link?

**Comment by jpivarski** [comment]
Found it, thanks.

**Comment by jpivarski** [comment]
I changed it using the GitHub editor, so it was a direct commit to master. I'm assuming that's okay for a small fix to non-code like this.
