### ISSUE TITLE
[Aurelius] Add Converters from Model Object to Complete PFA Doc

### ISSUE THREAD

**Issue by ReportMort** [opendatagroup/hadrian#28]
Currently, models generated with Aurelius cannot be converted directly from their state as an object into a valid PFA document. Is it possible to add S3 wrapper methods for model object types (e.g. `glm`, `lm`, etc.) that convert these models directly to a completely valid PFA document? This would decrease time in having to construct these simple models by hand from their object components as done in the tutorial:

https://github.com/opendatagroup/hadrian/wiki/Aurelius-glm

**Comment by jpivarski** [comment]
If you know how to do it--- i.e. how to extract the relevant parameters from the S3 objects--- then you know how to expand this function. If you can do that, please make a pull request.

...

You're faster than I am. You just submitted a pull request. I think it should be accepted, but someone from ODG will have to do it.

**Comment by ReportMort** [comment]
@jpivarski Thanks Jim! That sounds good. I started using PFA more from R and I think some wrapper functions plus documentation would make it easier for R users to adopt.
