### ISSUE TITLE
Release 0.8.5 was not published to maven repo

### ISSUE THREAD

**Issue by tovbinm** [opendatagroup/hadrian#56]
Howdy,

It seems that 0.8.5 released, but was not published to maven repo (http://repository.opendatagroup.com/maven/com/opendatagroup/hadrian/0.8.5/).

Additional question, are there any plans on releasing into Maven Central repository?

**Comment by mahowald-odg** [comment]
Hi,

Hadrian 0.8.5 is now available in Maven Central: http://repo1.maven.org/maven2/com/opendatagroup/hadrian/0.8.5/

**Comment by tovbinm** [comment]
Thank you so much!
