### ISSUE TITLE
Syntax error in PrettyPFA example in the wiki

### ISSUE THREAD

**Issue by jthompson6** [opendatagroup/hadrian#9]
In the example on the wiki page for PrettyPFA, if I try to copy-paste the code into my python terminal, it fails with `titus.errors.PrettyPfaException: Parsing syntax error`.

I realised this is because the return value in the else condition is accidentally commented out.
It says 
```
  else
    // otherwise, return null (N/A)        null
```
when it should be
```
  else
    // otherwise, return null (N/A)        
    null
```

As a side note (not sure if this is worth a ticket), is there a list of dependencies somewhere needed for titus? I only found through trial and error that I needed avro and ply, and I couldn't see anything about this in the instructions.

**Comment by collinbennett** [comment]
I fixed the PrettyPFA in the example.

**Comment by collinbennett** [comment]
As to your second question, all Titus dependencies are in the setup.py file.  If you have python's setup tools installed, running 

  `sudo python setup.py install`

 will install Titus from your local version of the source file  and pull down the dependencies.  Alternatively, you can get Titus using the Python package manager: 

  `pip install titus`

Please let me know if you have any trouble with these.

**Comment by jthompson6** [comment]
I used `sudo python setup.py install`. Looking at the output from that, I do now see a download error for ply, so I guess that was the problem, thanks.

**Comment by jthompson6** [comment]
It might be helpful to add the pip install option to the wiki though. I can't see anything about it in https://github.com/opendatagroup/hadrian/wiki/Installation#case-4-you-want-to-install-titus-in-python and it's probably simpler if it means you don't have to clone hadrian.

**Comment by collinbennett** [comment]
The pip install option is new (and the documentation hasn't been updated to reflect it yet) and it only provides the latest stable release, version 0.8.4.  But, with pip, we can only push snapshot releases, so if you want the daily branch or have local updates, then you will have to use setup.py.

I will update the install notes to let people know about pip.  I am trying to get Aurelius added to cran to make that simpler as well.
